[package]
name = "pa193project_team07"
version = "0.1.0"
authors = ["Štěpánka Gennertová, Pavel Novák, Tran Anh Minh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"